"""Per-code adapter specs for the thermal-transport DAG.

Each submodule holds the SpaceRepresentationSpec and OperatorRepresentationSpec instances
for one code (kaldo, phono3py, ...). All instances are constructed against
the shared operator DAG in `omai.thermal_transport.operator`, so cross-code
agreement is checked at the operator level (per Principle 7).

Re-exports the per-code spec instances for convenience; the canonical
location is the corresponding submodule (e.g.
`omai.thermal_transport.representation.kaldo`).
"""

from omai.thermal_transport.representation.kaldo import (
    KALDO_COMPUTE_FORCE_CONSTANTS_2,
    KALDO_COMPUTE_FORCE_CONSTANTS_3,
    KALDO_COMPUTE_HEAT_CAPACITY,
    KALDO_COMPUTE_LINEWIDTH,
    KALDO_FREQUENCY,
    KALDO_GROUP_VELOCITY,
    KALDO_HEAT_CAPACITY,
    KALDO_LINEWIDTH,
    KALDO_SOLVE_BTE_DIRECT,
    KALDO_THERMAL_CONDUCTIVITY_DIRECT,
    KALDO_THERMAL_CONDUCTIVITY_RTA,
    kaldo_compute_linewidth_spec,
)
from omai.thermal_transport.representation.mescal import (
    MESCAL_PHONON_TRANSMISSION,
    MESCAL_THERMAL_CONDUCTANCE_LANDAUER,
)
from omai.thermal_transport.representation.phono3py import (
    PHONO3PY_COMPUTE_FORCE_CONSTANTS_2,
    PHONO3PY_COMPUTE_FORCE_CONSTANTS_3,
    PHONO3PY_COMPUTE_HEAT_CAPACITY,
    PHONO3PY_COMPUTE_LINEWIDTH,
    PHONO3PY_FREQUENCY,
    PHONO3PY_GROUP_VELOCITY,
    PHONO3PY_HEAT_CAPACITY,
    PHONO3PY_LINEWIDTH,
    PHONO3PY_SOLVE_BTE_DIRECT,
    PHONO3PY_THERMAL_CONDUCTIVITY_DIRECT,
    PHONO3PY_THERMAL_CONDUCTIVITY_RTA,
)
from omai.thermal_transport.representation.phonopy import (
    PHONOPY_FREQUENCY,
    PHONOPY_MOLAR_HEAT_CAPACITY,
)
from omai.thermal_transport.representation.qe import (
    QE_APPLY_NAC_CORRECTION,
    QE_BARE_DYNAMICAL_MATRIX,
    QE_BORN_CHARGES,
    QE_COMPUTE_DISPERSION,
    QE_COMPUTE_DOS,
    QE_COMPUTE_DYNAMICAL_MATRIX,
    QE_COMPUTE_FORCE_CONSTANTS_2,
    QE_DIELECTRIC_TENSOR,
    QE_DYNAMICAL_MATRIX,
    QE_EIGENVECTORS,
    QE_FORCE_CONSTANTS_2,
    QE_FREQUENCY,
    QE_PHONON_DOS,
    QE_POTENTIAL,
)
from omai.thermal_transport.representation.qe_d3q import (
    QE_D3Q_COMPUTE_FORCE_CONSTANTS_3,
    QE_D3Q_COMPUTE_LINEWIDTH,
    QE_D3Q_FORCE_CONSTANTS_2,
    QE_D3Q_FORCE_CONSTANTS_3,
    QE_D3Q_LINEWIDTH,
    QE_D3Q_SOLVE_BTE_DIRECT,
    QE_D3Q_THERMAL_CONDUCTIVITY_DIRECT,
    QE_D3Q_THERMAL_CONDUCTIVITY_RTA,
)
from omai.thermal_transport.representation.shengbte import (
    SHENGBTE_COMPUTE_FORCE_CONSTANTS_2,
    SHENGBTE_COMPUTE_FORCE_CONSTANTS_3,
    SHENGBTE_COMPUTE_LINEWIDTH,
    SHENGBTE_FREQUENCY,
    SHENGBTE_GROUP_VELOCITY,
    SHENGBTE_LINEWIDTH,
    SHENGBTE_SOLVE_BTE_DIRECT,
    SHENGBTE_THERMAL_CONDUCTIVITY_DIRECT,
    SHENGBTE_THERMAL_CONDUCTIVITY_RTA,
    SHENGBTE_VOLUMETRIC_HEAT_CAPACITY,
)

__all__ = [
    "QE_APPLY_NAC_CORRECTION",
    "QE_BARE_DYNAMICAL_MATRIX",
    "QE_BORN_CHARGES",
    "QE_COMPUTE_DISPERSION",
    "QE_COMPUTE_DOS",
    "QE_COMPUTE_DYNAMICAL_MATRIX",
    "QE_COMPUTE_FORCE_CONSTANTS_2",
    "QE_DIELECTRIC_TENSOR",
    "QE_DYNAMICAL_MATRIX",
    "QE_EIGENVECTORS",
    "QE_FORCE_CONSTANTS_2",
    "QE_FREQUENCY",
    "QE_PHONON_DOS",
    "QE_POTENTIAL",
    "QE_D3Q_COMPUTE_FORCE_CONSTANTS_3",
    "QE_D3Q_COMPUTE_LINEWIDTH",
    "QE_D3Q_FORCE_CONSTANTS_2",
    "QE_D3Q_FORCE_CONSTANTS_3",
    "QE_D3Q_LINEWIDTH",
    "QE_D3Q_SOLVE_BTE_DIRECT",
    "QE_D3Q_THERMAL_CONDUCTIVITY_DIRECT",
    "QE_D3Q_THERMAL_CONDUCTIVITY_RTA",
    "KALDO_COMPUTE_FORCE_CONSTANTS_2",
    "KALDO_COMPUTE_FORCE_CONSTANTS_3",
    "KALDO_COMPUTE_HEAT_CAPACITY",
    "KALDO_COMPUTE_LINEWIDTH",
    "KALDO_FREQUENCY",
    "KALDO_GROUP_VELOCITY",
    "KALDO_HEAT_CAPACITY",
    "KALDO_LINEWIDTH",
    "KALDO_SOLVE_BTE_DIRECT",
    "KALDO_THERMAL_CONDUCTIVITY_DIRECT",
    "KALDO_THERMAL_CONDUCTIVITY_RTA",
    "kaldo_compute_linewidth_spec",
    "MESCAL_PHONON_TRANSMISSION",
    "MESCAL_THERMAL_CONDUCTANCE_LANDAUER",
    "PHONO3PY_COMPUTE_FORCE_CONSTANTS_2",
    "PHONO3PY_COMPUTE_FORCE_CONSTANTS_3",
    "PHONO3PY_COMPUTE_HEAT_CAPACITY",
    "PHONO3PY_COMPUTE_LINEWIDTH",
    "PHONO3PY_FREQUENCY",
    "PHONO3PY_GROUP_VELOCITY",
    "PHONO3PY_HEAT_CAPACITY",
    "PHONO3PY_LINEWIDTH",
    "PHONO3PY_SOLVE_BTE_DIRECT",
    "PHONO3PY_THERMAL_CONDUCTIVITY_DIRECT",
    "PHONO3PY_THERMAL_CONDUCTIVITY_RTA",
    "SHENGBTE_COMPUTE_FORCE_CONSTANTS_2",
    "SHENGBTE_COMPUTE_FORCE_CONSTANTS_3",
    "SHENGBTE_COMPUTE_LINEWIDTH",
    "SHENGBTE_FREQUENCY",
    "SHENGBTE_GROUP_VELOCITY",
    "SHENGBTE_LINEWIDTH",
    "SHENGBTE_SOLVE_BTE_DIRECT",
    "SHENGBTE_THERMAL_CONDUCTIVITY_DIRECT",
    "SHENGBTE_THERMAL_CONDUCTIVITY_RTA",
    "SHENGBTE_VOLUMETRIC_HEAT_CAPACITY",
    "PHONOPY_FREQUENCY",
    "PHONOPY_MOLAR_HEAT_CAPACITY",
]
