"""The index registry generator (kernel P3).

The index is the source registry that lives beside the map: one
`index/codes/<rep>.json` per representation, pinning each covered node to its
content-addressed uid at the store HEAD at generation time. `papers/` and
`experiments/` arrive with their first entries later; only `codes/` is
generated here.

Each file is `{"representation", "map_version", "covers": [{"node", "uid",
"api", "unit"} ...sorted by node], "aliases"?, "releases"?}`, where
`map_version` is the committed store's head version (head-at-generation: the
version the coverage was computed against, which advances past the frozen
genesis as contributions land), and `aliases` and `releases` project
`docs/data/releases/<rep>.json` when the representation has registered
releases. Files are generated by `python -m omai.index_data` and never
hand-edited.
"""
from __future__ import annotations

import json
from pathlib import Path

from omai.map_data import build_codes, build_graph_dict
from omai.store import Store

_REPO_ROOT = Path(__file__).resolve().parents[1]


def _map_version() -> str:
    """The store head at generation time: the version the coverage is
    computed against (not the frozen GENESIS, which the store grows past)."""
    return Store(_REPO_ROOT / "map").head


def _name_to_uid(domains) -> dict[str, str]:
    return {n["id"]: n["uid"] for n in build_graph_dict(domains)["nodes"]}


def _index_docs(domains) -> dict[str, dict]:
    """Build the per-representation index documents (representation -> doc)."""
    from omai.evidence import release_files
    from omai.map_data import _DOCS, _lineage_version

    releases = release_files(_DOCS / "data")
    map_version = _map_version()
    lineage_version = _lineage_version(map_version)
    name_to_uid = _name_to_uid(domains)
    codes = build_codes(domains)
    docs: dict[str, dict] = {}
    for rep, spaces in codes.items():
        covers = [
            {
                "node": space_name,
                "uid": name_to_uid[space_name],
                "api": info.get("api"),
                "unit": info.get("unit"),
            }
            for space_name, info in spaces.items()
        ]
        covers.sort(key=lambda e: e["node"])
        docs[rep] = {
            "representation": rep,
            # the unified schema version (graph + format rules); map_version
            # stays as the legacy key carrying the raw store head
            "lineage_version": lineage_version,
            "map_version": map_version,
            "covers": covers,
            **releases.get(rep, {}),
        }
    return docs


_README = """# index: the source registry

The index is the source registry that lives beside the map. Entries are
organized by source; each pins that source's coverage to a specific element
hash at a specific map version.

- `codes/`: one file per code representation, present now. Each
  `codes/<rep>.json` is `{representation, map_version, covers}`, where `covers`
  lists the nodes the code maps, each carrying the node uid, the code's API
  name, and its declared unit, sorted by node, and `map_version` is the store
  head at generation time (the version the coverage was computed against).
  A representation with registered releases also carries `aliases` (the
  registry row ids that name it) and `releases` (`{version, tag, commit,
  released, spdx, license_source}`, the licence read at the tag), projected
  from `docs/data/releases/<rep>.json`.
- `papers/` and `experiments/` arrive with their first entries later.

Files here are generated, never hand-edited: run `python -m omai.index_data`.
"""


def write_index(root: Path = Path("index")) -> Path:
    """Write `<root>/codes/<rep>.json` for every representation plus a README,
    removing the file of a representation that no longer exists.

    Returns the root directory. The map version stamped on every file is the
    store head at generation time.
    """
    from omai.map_data import DOMAINS

    root = Path(root)
    codes_dir = root / "codes"
    codes_dir.mkdir(parents=True, exist_ok=True)
    docs = _index_docs(DOMAINS)
    for rep, doc in docs.items():
        (codes_dir / f"{rep}.json").write_text(json.dumps(doc, indent=1))
    for stale in set(codes_dir.glob("*.json")) - {codes_dir / f"{rep}.json" for rep in docs}:
        stale.unlink()
    (root / "README.md").write_text(_README)
    return root


if __name__ == "__main__":
    print("wrote", write_index())
