/-
  OpenMaterials: the units bridge to physlib.

  Generated by omai.lean_units from map version 693a10d28fc2.
  The map stores values in SI-scaled canonical units (each Unit's si_scale in
  omai/representation/units.py). physlib's dimScale is the conversion factor
  between unit systems. These theorems anchor the map's convention: converting
  from our canonical system (SI) to SI is the identity, and conversions between
  any two systems round-trip. Compiles against physlib (Lean 4.31.0).

  A sample of the map's canonical units (si_scale = 1):
  -- J_per_K : canonical for energy_per_temperature
  -- J_per_K_per_mol : canonical for energy_per_temperature_per_mole
  -- J_per_m3_per_K : canonical for energy_per_temperature_per_volume
  -- J_per_mol : canonical for energy_per_mole
  -- W_per_K : canonical for thermal_conductance
  -- W_per_m2_k : canonical for interface_conductance
  -- W_per_m_per_K : canonical for thermal_conductivity
  -- coulomb : canonical for electric_charge
  -- dimensionless : canonical for dimensionless
  -- joule : canonical for energy
  -- kelvin : canonical for temperature
  -- m2_per_s : canonical for diffusivity

  physlib (leanprover-community/physlib), successor of PhysLean by
  Joseph Tooby-Smith, Apache 2.0.
-/
import Physlib.Units.Basic

namespace OpenMaterials.Units

open Dimension UnitChoices

/-- The map's canonical unit system is SI: a stored value is already in SI
    units, so converting it to SI is the identity for every dimension. -/
theorem canonical_is_identity (d : Dimension) : dimScale SI SI d = 1 :=
  dimScale_self SI d

/-- Conversions compose: a value converted through an intermediate unit system
    equals the direct conversion. Round-trips (u1 -> u2 -> u1) therefore cancel. -/
theorem conversions_compose (u1 u2 u3 : UnitChoices) (d : Dimension) :
    dimScale u1 u2 d * dimScale u2 u3 d = dimScale u1 u3 d :=
  dimScale_transitive u1 u2 u3 d

/-- The trivial dimension (dimensionless) never scales under any unit change. -/
theorem dimensionless_never_scales (u1 u2 : UnitChoices) :
    dimScale u1 u2 1 = 1 :=
  dimScale_one u1 u2

end OpenMaterials.Units
