/-
  OpenMaterials: the seven-base dimensional layer, Mathlib only.

  Generated by omai.physlean_export from map version fc862ac975c1.
  physlib's Dimension has five bases, so nodes whose dimension uses
  amount-of-substance (N), electric current (I), or luminous intensity (J)
  are omitted from OpenMaterials.lean. This module defines the map's full
  seven-base dimension vector (M, L, T, Th, N, I, J) and proves the
  dimensional identities for exactly those omitted nodes. Requires only
  Mathlib (Lean 4.31.0).
-/
import Mathlib.Tactic

namespace OpenMaterials

/-- The map's seven-base dimension vector, in the map's base order:
    mass, length, time, temperature, amount of substance, electric
    current, luminous intensity. -/
structure Dimension7 where
  /-- The mass dimension (M). -/
  M : ℚ
  /-- The length dimension (L). -/
  L : ℚ
  /-- The time dimension (T). -/
  T : ℚ
  /-- The temperature dimension (Th). -/
  Th : ℚ
  /-- The amount-of-substance dimension (N). -/
  N : ℚ
  /-- The electric-current dimension (I). -/
  I : ℚ
  /-- The luminous-intensity dimension (J). -/
  J : ℚ

namespace Dimension7

@[ext]
lemma ext {d1 d2 : Dimension7}
    (hM : d1.M = d2.M) (hL : d1.L = d2.L) (hT : d1.T = d2.T)
    (hTh : d1.Th = d2.Th) (hN : d1.N = d2.N) (hI : d1.I = d2.I)
    (hJ : d1.J = d2.J) : d1 = d2 := by
  cases d1
  cases d2
  congr

instance : Mul Dimension7 where
  mul d1 d2 := ⟨d1.M + d2.M, d1.L + d2.L, d1.T + d2.T, d1.Th + d2.Th,
    d1.N + d2.N, d1.I + d2.I, d1.J + d2.J⟩

@[simp]
lemma M_mul (d1 d2 : Dimension7) : (d1 * d2).M = d1.M + d2.M := rfl

@[simp]
lemma L_mul (d1 d2 : Dimension7) : (d1 * d2).L = d1.L + d2.L := rfl

@[simp]
lemma T_mul (d1 d2 : Dimension7) : (d1 * d2).T = d1.T + d2.T := rfl

@[simp]
lemma Th_mul (d1 d2 : Dimension7) : (d1 * d2).Th = d1.Th + d2.Th := rfl

@[simp]
lemma N_mul (d1 d2 : Dimension7) : (d1 * d2).N = d1.N + d2.N := rfl

@[simp]
lemma I_mul (d1 d2 : Dimension7) : (d1 * d2).I = d1.I + d2.I := rfl

@[simp]
lemma J_mul (d1 d2 : Dimension7) : (d1 * d2).J = d1.J + d2.J := rfl

end Dimension7

-- The nodes physlib cannot express, as seven-base constants
-- (map base order: M, L, T, Th, N, I, J).
def CalphadMolarEntropy : Dimension7 := ⟨1, 2, (-2 : ℚ), (-1 : ℚ), (-1 : ℚ), 0, 0⟩  -- CalphadMolarEntropy
def CarrierMobility : Dimension7 := ⟨(-1 : ℚ), 0, 2, 0, 0, 1, 0⟩  -- CarrierMobility
def ChemicalPotential : Dimension7 := ⟨1, 2, (-2 : ℚ), 0, (-1 : ℚ), 0, 0⟩  -- ChemicalPotential
def ElectricalConductivity_carrier_electronic : Dimension7 := ⟨(-1 : ℚ), (-3 : ℚ), 3, 0, 0, 2, 0⟩  -- ElectricalConductivity[carrier=electronic]
def ElectricalConductivity_carrier_ionic : Dimension7 := ⟨(-1 : ℚ), (-3 : ℚ), 3, 0, 0, 2, 0⟩  -- ElectricalConductivity[carrier=ionic]
def HeatCapacityConstantP : Dimension7 := ⟨1, 2, (-2 : ℚ), (-1 : ℚ), (-1 : ℚ), 0, 0⟩  -- HeatCapacityConstantP
def MagneticMoment : Dimension7 := ⟨0, 2, 0, 0, 0, 1, 0⟩  -- MagneticMoment
def MolarEnthalpy : Dimension7 := ⟨1, 2, (-2 : ℚ), 0, (-1 : ℚ), 0, 0⟩  -- MolarEnthalpy
def MolarEntropy : Dimension7 := ⟨1, 2, (-2 : ℚ), (-1 : ℚ), (-1 : ℚ), 0, 0⟩  -- MolarEntropy
def MolarGibbsEnergy : Dimension7 := ⟨1, 2, (-2 : ℚ), 0, (-1 : ℚ), 0, 0⟩  -- MolarGibbsEnergy
def MolarHeatCapacity : Dimension7 := ⟨1, 2, (-2 : ℚ), (-1 : ℚ), (-1 : ℚ), 0, 0⟩  -- MolarHeatCapacity
def MolarHelmholtzFreeEnergy : Dimension7 := ⟨1, 2, (-2 : ℚ), 0, (-1 : ℚ), 0, 0⟩  -- MolarHelmholtzFreeEnergy
def MolarInternalEnergy : Dimension7 := ⟨1, 2, (-2 : ℚ), 0, (-1 : ℚ), 0, 0⟩  -- MolarInternalEnergy
def MolarVolume : Dimension7 := ⟨0, 3, 0, 0, (-1 : ℚ), 0, 0⟩  -- MolarVolume
def QHAGibbsEnergy : Dimension7 := ⟨1, 2, (-2 : ℚ), 0, (-1 : ℚ), 0, 0⟩  -- QHAGibbsEnergy
def SeebeckCoefficient : Dimension7 := ⟨1, 2, (-3 : ℚ), (-1 : ℚ), 0, (-1 : ℚ), 0⟩  -- SeebeckCoefficient
def Voltage : Dimension7 := ⟨1, 2, (-3 : ℚ), 0, 0, (-1 : ℚ), 0⟩  -- Voltage

-- Edge dimensional identities among the omitted nodes: output dimension
-- = product of input dimensions, by ext + simp, as in OpenMaterials.lean.
theorem edge_compute_chemical_potentials_to_ChemicalPotential : ChemicalPotential = MolarGibbsEnergy := by
  apply Dimension7.ext <;> simp [ChemicalPotential, MolarGibbsEnergy]

end OpenMaterials
