/-
  OpenMaterials: the map's dimensional layer, verified in Lean.

  Generated by omai.physlean_export from map version 693a10d28fc2.
  This file COMPILES against physlib (Lean 4.31.0): each node is a
  physlib Dimension and each theorem states an edge's output dimension
  equals the product of its input dimensions, proved by ext + simp. Nodes whose
  dimension uses amount-of-substance, current, or luminous intensity are
  omitted: physlib's Dimension has no base for them (see the module).

  physlib (leanprover-community/physlib), successor of PhysLean by
  Joseph Tooby-Smith, Apache 2.0.
-/
import Physlib.Units.Dimension

namespace OpenMaterials

open Dimension

-- Nodes as dimensioned constants (physlib field order: length, time, mass, charge, temperature).
def ActivationEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- ActivationEnergy
def AdsorptionEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- AdsorptionEnergy
def BandGap : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- BandGap
def BareDynamicalMatrix : Dimension := ⟨0, (-2 : ℚ), 0, 0, 0⟩  -- BareDynamicalMatrix
def BondDissociationEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- BondDissociationEnergy
def BornCharges : Dimension := ⟨0, 0, 0, 0, 0⟩  -- BornCharges
def BulkModulus : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- BulkModulus
def CarrierDensity : Dimension := ⟨(-3 : ℚ), 0, 0, 0, 0⟩  -- CarrierDensity
def ConductanceDriftExponent : Dimension := ⟨0, 0, 0, 0, 0⟩  -- ConductanceDriftExponent
def ConductanceWindow : Dimension := ⟨0, 0, 0, 0, 0⟩  -- ConductanceWindow
def ConfigurationalEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- ConfigurationalEnergy
def CumulativeKappa_wrt_mfp : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- CumulativeKappa[wrt=mfp]
def CumulativeKappa_wrt_omega : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- CumulativeKappa[wrt=omega]
def DepolarizationFactor : Dimension := ⟨0, 0, 0, 0, 0⟩  -- DepolarizationFactor
def DielectricTensor : Dimension := ⟨0, 0, 0, 0, 0⟩  -- DielectricTensor
def Diffusivity : Dimension := ⟨2, (-1 : ℚ), 0, 0, 0⟩  -- Diffusivity
def DotProductError : Dimension := ⟨0, 0, 0, 0, 0⟩  -- DotProductError
def DynamicalMatrix : Dimension := ⟨0, (-2 : ℚ), 0, 0, 0⟩  -- DynamicalMatrix
def Eigenvectors : Dimension := ⟨0, 0, 0, 0, 0⟩  -- Eigenvectors
def ElasticConstants : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- ElasticConstants
def ElectronAffinity : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- ElectronAffinity
def ElectronicDOS : Dimension := ⟨(-2 : ℚ), 2, (-1 : ℚ), 0, 0⟩  -- ElectronicDOS
def ElectronicThermalConductivity : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ElectronicThermalConductivity
def EnergyAboveHull : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- EnergyAboveHull
def Entropy : Dimension := ⟨2, (-2 : ℚ), 1, 0, (-1 : ℚ)⟩  -- Entropy
def FillerVolumeFraction : Dimension := ⟨0, 0, 0, 0, 0⟩  -- FillerVolumeFraction
def ForceConstants_order_2 : Dimension := ⟨0, (-2 : ℚ), 1, 0, 0⟩  -- ForceConstants[order=2]
def ForceConstants_order_3 : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- ForceConstants[order=3]
def Forces : Dimension := ⟨1, (-2 : ℚ), 1, 0, 0⟩  -- Forces
def FormationEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- FormationEnergy
def Frequency : Dimension := ⟨0, (-1 : ℚ), 0, 0, 0⟩  -- Frequency
def GrainBoundaryEnergy : Dimension := ⟨0, (-2 : ℚ), 1, 0, 0⟩  -- GrainBoundaryEnergy
def GroupVelocity : Dimension := ⟨1, (-1 : ℚ), 0, 0, 0⟩  -- GroupVelocity
def Gruneisen : Dimension := ⟨0, 0, 0, 0, 0⟩  -- Gruneisen
def HOMOLUMOGap : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- HOMOLUMOGap
def HeatCapacity : Dimension := ⟨2, (-2 : ℚ), 1, 0, (-1 : ℚ)⟩  -- HeatCapacity
def HeatCapacity_method_pimd : Dimension := ⟨2, (-2 : ℚ), 1, 0, (-1 : ℚ)⟩  -- HeatCapacity[method=pimd]
def HeatCurrent : Dimension := ⟨3, (-3 : ℚ), 1, 0, 0⟩  -- HeatCurrent
def HelmholtzFreeEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- HelmholtzFreeEnergy
def InterfaceConductance : Dimension := ⟨0, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- InterfaceConductance
def InternalEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- InternalEnergy
def IsotopeAbundances : Dimension := ⟨0, 0, 0, 0, 0⟩  -- IsotopeAbundances
def Linewidth_channel_anharmonic_3ph : Dimension := ⟨0, (-1 : ℚ), 0, 0, 0⟩  -- Linewidth[channel=anharmonic_3ph]
def Linewidth_channel_boundary : Dimension := ⟨0, (-1 : ℚ), 0, 0, 0⟩  -- Linewidth[channel=boundary]
def Linewidth_channel_isotope : Dimension := ⟨0, (-1 : ℚ), 0, 0, 0⟩  -- Linewidth[channel=isotope]
def Linewidth_channel_total : Dimension := ⟨0, (-1 : ℚ), 0, 0, 0⟩  -- Linewidth[channel=total]
def MassDensity : Dimension := ⟨(-3 : ℚ), 0, 1, 0, 0⟩  -- MassDensity
def MeanFreeDisplacement_bte_solver_direct_inverse : Dimension := ⟨1, 0, 0, 0, 0⟩  -- MeanFreeDisplacement[bte_solver=direct_inverse]
def MeanFreeDisplacement_bte_solver_rta : Dimension := ⟨1, 0, 0, 0, 0⟩  -- MeanFreeDisplacement[bte_solver=rta]
def MeanSquaredDisplacement : Dimension := ⟨2, 0, 0, 0, 0⟩  -- MeanSquaredDisplacement
def ModalDiffusivity : Dimension := ⟨2, (-1 : ℚ), 0, 0, 0⟩  -- ModalDiffusivity
def MolecularFrequency : Dimension := ⟨0, (-1 : ℚ), 0, 0, 0⟩  -- MolecularFrequency
def ParticipationRatio : Dimension := ⟨0, 0, 0, 0, 0⟩  -- ParticipationRatio
def PhaseFraction : Dimension := ⟨0, 0, 0, 0, 0⟩  -- PhaseFraction
def PhaseSpace3Phonon : Dimension := ⟨0, 1, 0, 0, 0⟩  -- PhaseSpace3Phonon
def PhononDOS : Dimension := ⟨0, 1, 0, 0, 0⟩  -- PhononDOS
def PhononTransmission : Dimension := ⟨0, 0, 0, 0, 0⟩  -- PhononTransmission
def PoissonRatio : Dimension := ⟨0, 0, 0, 0, 0⟩  -- PoissonRatio
def PotentialOfMeanForce : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- PotentialOfMeanForce
def PowerFactor : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-2 : ℚ)⟩  -- PowerFactor
def Pressure : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- Pressure
def ProgrammingPulseEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- ProgrammingPulseEnergy
def QuantumKineticEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- QuantumKineticEnergy
def ReactionBarrier_construction_neb_mep : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- ReactionBarrier[construction=neb_mep]
def ReactionEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- ReactionEnergy
def SchottkyBarrierHeight_band_carrier_electron : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- SchottkyBarrierHeight[band_carrier=electron]
def ShearModulus : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- ShearModulus
def StateCoefficientOfVariation : Dimension := ⟨0, 0, 0, 0, 0⟩  -- StateCoefficientOfVariation
def StaticDielectricTensor : Dimension := ⟨0, 0, 0, 0, 0⟩  -- StaticDielectricTensor
def Stress : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- Stress
def SurfaceEnergy : Dimension := ⟨0, (-2 : ℚ), 1, 0, 0⟩  -- SurfaceEnergy
def Temperature : Dimension := ⟨0, 0, 0, 0, 1⟩  -- Temperature
def ThermalConductance_transport_model_landauer : Dimension := ⟨2, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductance[transport_model=landauer]
def ThermalConductivity : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity
def ThermalConductivity_bte_solver_direct_inverse : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[bte_solver=direct_inverse]
def ThermalConductivity_bte_solver_rta : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[bte_solver=rta]
def ThermalConductivity_contribution_total : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[contribution=total]
def ThermalConductivity_effective_medium_nan_orientation_aligned : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[effective_medium=nan,orientation=aligned]
def ThermalConductivity_effective_medium_nan_orientation_random : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[effective_medium=nan,orientation=random]
def ThermalConductivity_role_filler : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[role=filler]
def ThermalConductivity_role_matrix : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[role=matrix]
def ThermalConductivity_transport_model_green_kubo : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=green_kubo]
def ThermalConductivity_transport_model_hnemd : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=hnemd]
def ThermalConductivity_transport_model_nemd : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=nemd]
def ThermalConductivity_transport_model_qhgk : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=qhgk]
def ThermalConductivity_transport_model_wigner : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=wigner]
def ThermalConductivity_transport_model_wigner_coherences : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=wigner_coherences]
def ThermalConductivity_transport_model_wigner_populations : Dimension := ⟨1, (-3 : ℚ), 1, 0, (-1 : ℚ)⟩  -- ThermalConductivity[transport_model=wigner_populations]
def ThermalExpansion : Dimension := ⟨0, 0, 0, 0, (-1 : ℚ)⟩  -- ThermalExpansion
def ThermalGruneisen : Dimension := ⟨0, 0, 0, 0, 0⟩  -- ThermalGruneisen
def TotalEnergy : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- TotalEnergy
def Trajectory : Dimension := ⟨1, 0, 0, 0, 0⟩  -- Trajectory
def TransitionTemperature : Dimension := ⟨0, 0, 0, 0, 1⟩  -- TransitionTemperature
def VolumetricHeatCapacity : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, (-1 : ℚ)⟩  -- VolumetricHeatCapacity
def WorkFunction : Dimension := ⟨2, (-2 : ℚ), 1, 0, 0⟩  -- WorkFunction
def YoungsModulus : Dimension := ⟨(-1 : ℚ), (-2 : ℚ), 1, 0, 0⟩  -- YoungsModulus
def ZT : Dimension := ⟨0, 0, 0, 0, 0⟩  -- ZT

-- Edge dimensional identities: output dimension = product of input
-- dimensions. Proved by extensionality on the five Dimension fields, then
-- simp with physlib's *_mul lemmas and the node definitions.
theorem edge_apply_nac_correction_to_DynamicalMatrix : DynamicalMatrix = BareDynamicalMatrix * BornCharges * DielectricTensor := by
  apply Dimension.ext <;> simp [DynamicalMatrix, BareDynamicalMatrix, BornCharges, DielectricTensor]
theorem edge_compute_isotope_scattering_to_Linewidth_channel_isotope : Linewidth_channel_isotope = Eigenvectors * Frequency * IsotopeAbundances := by
  apply Dimension.ext <;> simp [Linewidth_channel_isotope, Eigenvectors, Frequency, IsotopeAbundances]
theorem edge_compute_participation_ratio_to_ParticipationRatio : ParticipationRatio = Eigenvectors := by
  apply Dimension.ext <;> simp [ParticipationRatio, Eigenvectors]
theorem edge_compute_reaction_energy_to_ReactionEnergy : ReactionEnergy = FormationEnergy := by
  apply Dimension.ext <;> simp [ReactionEnergy, FormationEnergy]
theorem edge_compute_transition_temperature_to_TransitionTemperature : TransitionTemperature = PhaseFraction * Temperature := by
  apply Dimension.ext <;> simp [TransitionTemperature, PhaseFraction, Temperature]
theorem edge_contract_bulk_modulus_to_BulkModulus : BulkModulus = ElasticConstants := by
  apply Dimension.ext <;> simp [BulkModulus, ElasticConstants]
theorem edge_contract_pressure_to_Pressure : Pressure = Stress := by
  apply Dimension.ext <;> simp [Pressure, Stress]
theorem edge_contract_shear_modulus_to_ShearModulus : ShearModulus = ElasticConstants := by
  apply Dimension.ext <;> simp [ShearModulus, ElasticConstants]
theorem edge_identity_dm_to_DynamicalMatrix : DynamicalMatrix = BareDynamicalMatrix := by
  apply Dimension.ext <;> simp [DynamicalMatrix, BareDynamicalMatrix]
theorem edge_propagate_programming_error_to_DotProductError : DotProductError = ConductanceWindow * StateCoefficientOfVariation := by
  apply Dimension.ext <;> simp [DotProductError, ConductanceWindow, StateCoefficientOfVariation]
theorem edge_resolve_effective_conductivity_to_ThermalConductivity : ThermalConductivity = ThermalConductivity_effective_medium_nan_orientation_random := by
  apply Dimension.ext <;> simp [ThermalConductivity, ThermalConductivity_effective_medium_nan_orientation_random]
theorem edge_resolve_thermal_conductivity_to_ThermalConductivity : ThermalConductivity = ThermalConductivity_bte_solver_direct_inverse := by
  apply Dimension.ext <;> simp [ThermalConductivity, ThermalConductivity_bte_solver_direct_inverse]

end OpenMaterials
